Add files via upload
Every time I try and push from commandline I get error messages like :To https://github.com/13mjward/CISC275-Spring2019-first-git
 ! [rejected]        master -> master (non-fast-forward)
error: failed to push some refs to 'https://github.com/13mjward/CISC275-Spring2019-first-git'
hint: Updates were rejected because the tip of your current branch is behind
hint: its remote counterpart. Integrate the remote changes (e.g.
hint: 'git pull ...') before pushing again.
hint: See the 'Note about fast-forwards' in 'git push --help' for details.

It's extremely frustrating when this happens, and if only we were taught how to use this kind of stuff instead of having to figure it out all alone.